// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _mig_deleteStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_mig_deleteStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202407311519213__mig_deleteStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
